name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Action'
        required: true
        

      instance_type:
        description: 'Enter EC2 Instance Type'
        required: true
        

      aws_region:
        description: 'Enter AWS Region'
        required: true
        

      


      
        


jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create Lambda Package
        run: |
          zip -r terraform/lambda.zip . -x ".git/*" -x "terraform/.terraform/"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="instance_type=${{ github.event.inputs.instance_type  }}" \
            -var="aws_region=${{ github.event.inputs.aws_region  }}" \
            
            

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
            
            

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          cd terraform
          terraform destroy -auto-approve \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
           
            

      - name: Deploy Lambda Function
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          aws lambda update-function-code \
            --function-name ec2-monitor-function \
            --zip-file fileb://terraform/lambda.zip

